transport/interface.go, transport/transport.go
Now we can buffer EIO packets before we send them. 
This allows for collecting packets before sending a 
connect packet.
=> Add underlining buffering to SIO transports

protocol/packet.pac.data.go, protocol/packet.pac.stream.go, protocol/packet.v5_test.go, protocol/utility.go
Add a test to make sure that non-namespaced ACKs work as expected.
Fix the difference between a stream and a ACK.
Add the Len() knowledge of a packet for ints and floats
=> Update the SIO protocol to be more fleshed out

engineio/protocol/packet.v3.go, engineio/transport/transport.polling.go
**Fix** the `HandshakeV3` protocol by changing it to a pointer so that changes
can be reflected when updated and so that the type matches when checking
the packet data during the type conversion to the wire representation 
(bytes).
**Fix** the polling transport so that it sends more than one packet in
a payload when there are several packets in the queue.
=> Fix EIO protocol Handshake and  HTTP Polling

engineio/option.v2.go, engineio/server.v3.go, engineio/server.v4.go, engineio/server.v5.go
**Update** the EIO server so that it can look through previous server
versions when applying functional options to a server version. Now
later versions of the server can use a functional option for a previous
version.
There was a bug in how the functional option was applied previously.
While previous versions would get the option applied it would be overwritten
by later versions as they were initialized. Because the later server
versions did not match the version of the server the functional option
could apply to, it would not reflect the change that the functional
option intended. This is now mitigated by looking though previous
versions of the server that the functional option is applied to.
**:label: NOTE:** Because we are looking through every functional option on every
previous …
=> EIO functional options version compatibility

callback/callback.go, serialize/serialize.go
**Add** the callback FuncString type `func(string)` so that they don't need to be created
by users each time.
**Add** the serialize Convert type `[]Serialize` to ease conversions of
variadic inputs.
**Update** parameter inputs to allow `float64` in the standard reflection 
based callback wrapper
=> New callback and serialize types & float64 params

callback/callback.go
Before an unknown parameter would create an `ErrBadParamType`. That
prevented passing objects and maps. Now it will just pass the value of
the parameter through, without an error.
=> Allow any value for a parameter

protocol/packet.pac.ns.go, protocol/packet.v2.msgpack.go, protocol/packet.v2_test.go, protocol/packet.v3.go, protocol/packet.v4.go, protocol/packet.v5.go
**Add** the ReadBinary method to satisfy a ReadBinary interface to allow SIO packet version 4 and 5 to accept binary data from clients.
**Update** the namespace struct so that the Len() count is accurate for empty namespaces.
**Fix** the msgpack logic so that it can accept non-base64 encoded data values.
**Add** a Reader that can propagate errors from io.Copy to the reader, so that any errors can be properly managed even if it comes from the io.Copy embedded within a go-routine.
=> Add ReadBinary interface and small fixes

engineio/error.go, engineio/protocol/handshake.v2.go, engineio/protocol/handshake.v3.go, engineio/protocol/packet.go, engineio/protocol/payload.v3.go, engineio/server.v2.go, engineio/server.v3.go
**Fix** issues around calculating the length of the pingTimeout and pingInterval values (as seconds).
**Refactor** the PayloadV3 to remove duplicate code, and push the processing to PayloadV2 as expected.
**Update** the EOH error to include the current SessionID so that it can be used to populate the SIO transport before it's called the second time. This allows for SIO v2 auto connections during the Handshake phase.
=> Fix EIO Protocol Len() sum and EOH sessionIDs

adaptor/transport/map/transport.go, engineio/protocol/handshake.v2.go, engineio/protocol/utility.go, engineio/protocol/utility.json.go, server.v1.go, server.v2.go, server.v3.go, server.v4.go
Removes race conditions from the code found by using -race in testing.
Removes the CopyRuneN function that required using a go routine to work
if favor of using a LimitedReader which doesn't require a go routine and
potentially cause race conditions.
=> Fix -race conditions

protocol/packet.pac.data.go
When using a string data object, `Len() int` would under report the
length by 2 characters, because the quote marks were not being taken
into account.
=> Fix the len value for string Data objects

engineio/protocol/packet.go, engineio/protocol/packet.v2.codec.go, engineio/protocol/packet.v2.go, engineio/protocol/packet.v3.go, engineio/protocol/packet.v4.go, engineio/protocol/payload.go, engineio/protocol/payload.v2.go, engineio/protocol/payload.v2.rw.go, engineio/protocol/payload.v3.codec.go, engineio/protocol/payload.v3.go, engineio/protocol/payload.v3.rw.go, engineio/protocol/payload.v4.go, engineio/transport/utility.go, internal/readwriter/read.decode.go, internal/readwriter/read.go, internal/readwriter/write.encode.go, internal/readwriter/write.go
Updates the EngineIO protocol and payload encoding/decoding methods to
be more clear. Updates the Binary support to not be based on if the
packet is Binary but rather if the protocol supports binary.
Updates the JSON and Base64 encoding to satisfy a common interface and
be added to the rw.Writer and rw.Reader structs so they can be used in
a fluid manner.
=> Refactor Protocol/Payload - decoding/encoding

adaptor/transport/map/transport_test.go, callback/callback_test.go, engineio/protocol/packet.v2_test.go, engineio/protocol/packet.v3_test.go, engineio/protocol/packet.v4_test.go, engineio/protocol/packet_test.go, engineio/protocol/payload.v2_test.go, engineio/protocol/payload.v3_test.go, engineio/protocol/payload.v4_test.go, engineio/protocol/utility_test.go, engineio/server.v2_test.go, engineio/server.v3_test.go, engineio/transport/transport.polling_test.go, engineio/transport/transport.websocket_test.go, internal/test/runner.go, protocol/packet.v1_test.go, protocol/packet.v2_test.go, protocol/packet.v3_test.go, protocol/packet.v4_test.go, protocol/packet.v5_test.go, serialize/serialize_test.go, server.v1_test.go, server.v2_test.go, server.v3_test.go, server.v4_test.go, server_test.go
All tests are updated to look similar and follow the same `t.Run`
sub-test format. Also this commit expands the test coverage for
Callable and Serializable through examples.
=> Refactor and add tests

adaptor/transport/memory/transport_test.go, engineio/option.v2.go, engineio/protocol/packet.v2.go, engineio/server.go, engineio/server.v2.go, engineio/server.v3.go, engineio/server.v4.go, engineio/session/manage.go, engineio/sessions.go, engineio/transport/error.go, engineio/transport/option.go, engineio/transport/transport.go, engineio/transport/transport.polling.go, engineio/transport/transport.polling_test.go, engineio/transport/transport.websocket.go, engineio/transport/utility.go, internal/readwriter/write.go, internal/readwriter/write.method.go, protocol/error.go, protocol/scratch.go, server.v1.go, server.v1.runback.go, server.v1_test.go, server.v2.runback.go, server.v2_test.go, server.v3.runback.go, server.v3_test.go, server.v4.runback.go, server.v4_test.go, server_test.go
Move interval and timeouts out of the HTTP polling transport and into sessions Allow errors to flow from the transport to the SIO server Fix option flows for the EIO server and EIO transports Update unit tests (removing websocket until later)
TODO(njones): Move the error flow from the transport to a side channel (and not tunnelled through the protocol Data packets)
=> Update sessions and interval polling in transport

engineio/server.v4.go, engineio/session/manage.go, engineio/session/session.go, engineio/sessions.go, engineio/transport/transport.go, engineio/transport/transport.polling.go, engineio/transport/transport.websocket.go, go.mod, go.sum
Sending a close type to an EIO polling or websocket transport will now close all connections in roughly the correct order.
=> Update the EIO polling and websocket Close type

serialize/serialize.go, server.v4.go, server.v4.runback.go, server.v4.socket.go
This adds handshake data to the SocketV4 struct. This is the initial auth data that is present only in v4. Other data can be back ported to other versions as needed.
=> Add handshake data to *SocketV4

.gitignore, callback/callback.go, serialize/serialize.go, server.v1.runback.go
The functionality around disconnecting a SIO packet was broken. These changes fix that and allow namespaced and non-namespaced disconnects to happen.
=> Update the SIO disconnect packet functionality

callback/callback.go, engineio/option.v2.go, engineio/server.v2.go, engineio/session/manage.go, engineio/sessions.go, engineio/transport/option.go, engineio/transport/transport.websocket.go, server.v1.runback.go, server.v1.socket.go, server.v2.runback.go, server.v4.runback.go, server.v4.socket.go, transport/transport.go, utility.go
This commit fixes returning binary data from an Emit or Ack callback. It also adds an exported generic Callback wrapper that can be used for On events. So callbacks can accept interface parameters if needed. The binary websocket transport can offer a buffered or unbuffered reader.
=> Fix binary ws transport and add new callback types

engineio/option.go, engineio/option.v2.go, engineio/option.v3.go, engineio/option.v4.go, engineio/server.go, engineio/server.v2.go, engineio/server.v3.go, engineio/server.v4.go, engineio/server.v5.go, engineio/transport/option.go, engineio/transport/transport.polling.go, engineio/transport/transport.websocket.go, option/option.go, server.v1.go, server.v1.new.go, server.v2.go, server.v2.new.go, server.v3.go, server.v3.new.go, server.v4.go, server.v4.new.go, server.v4.runback.go, transport/filter.go, transport/option.go
Refactor most functional options to use the same underlining interface which will help with inter-op and passing them along. For instance, now a transport functional option can be passed in during the SocketIO server setup. Also, simplified the execution path for applying options previously it was a O(n^n) application process of options. This has been simplified to O(n*m), and gives a much more logical execution path of when an option will be applied.
=> Update functional options

engineio/sessions.go, server.v1.go, server.v1.runback.go, server.v1.socket.go, server.v1_test.go, server.v2.go, server.v2.runback.go, server.v2.socket.go, server.v2_test.go, server.v3.go, server.v3.runback.go, server.v3_test.go, server.v4.go, server.v4.runback.go, server.v4.socket.go, server.v4_test.go
Fix  Data Race Conditions in all Server Versions
When the tests for websockets were added, it exposed a Data Race that could happen when using the inSocketV(x) data structures. A RWMutex was added to guard access around the fields that could cause trouble. Also the tests were updated to increment counters using atomic to prevent race conditions within the test code. There needed to be atomic access around the interval duration in the sessions management code for EIO transports. This is a wrapper around int64 atomic code.
=> Fix data race conditions all server versions

serialize/serialize.go
There are security issues found by Github code scanning. This commit fixes those issues.
Fixes:
Code scanning alerts #1
Code scanning alerts #2
=> Fixing the int/uint size for security reasons

callback/error.go, engineio/error.go, engineio/protocol/error.go, engineio/protocol/packet.v2.go, engineio/server.v2.go, engineio/transport/error.go, error.go, internal/errors/errors.go, protocol/error.go, serialize/error.go, server.v1.go
* Added a State type for errors, so that they can be managed as a type through the socketio package HTTP handler 
* Refactored the HTTP 400 errors so they don't appear so complicated, and can be managed as a prefix through the socketio package HTTP handler
*  Moved a few functions and error strings around, to increase code readability
=> A lightweight errors refactor

internal/errors/errors.go, server.v4.runback.go
Added StringF Is method error matching, to the internal errors.Struct object This fixes an issue in `server.v4.runback.go` where the wrong error message was being sent back, because the Is method was broken for StringF errors.
Uses "%valid", "Inv" to produce "Invalid" with a capital letter for the error message, which is marked as incorrect by the go linter. The "%v" with "alid" produces a valid word while providing a valid formatting option to provide a string.
=> Update error handling for errors.Struct Is method

engineio/transport/transport.go, engineio/transport/transport.polling.go, server.v1.runback.go
Removed the polling only auto-connect for namespaces (this is why it wasn't working for the websocket transport). Also fixed a small issue with version3 Payload encoding, where the packet length was not being reported for NOOP packets.
[fixes #60]
[fixes #61]
=> Fix the namespace auto-connect in SocketIO v2 & v3

server.v1_test.go, server.v2_test.go, server_test.go
The tests before were suppressing polling auto-connect messages. Those are now being captured, and the tests have been updated to account for the extra messages.
=> Update tests to allow for auto-connect namespaces

engineio/protocol/packet.v2_test.go, internal/test/runner.go, protocol/packet.go, protocol/packet.pac.ns.go, protocol/packet.v1_test.go, protocol/packet.v2_test.go, protocol/packet.v3_test.go, protocol/packet.v4_test.go, protocol/packet.v5_test.go, protocol/scratch.go, server.v1.go, server.v1.runback.go, server.v1_test.go, server.v2.go, server.v2.runback.go, server.v2_test.go, server_test.go
- Fix the SocketIO connect protocol 
- Update SocketIO server and packet tests
When SocketIO connects to a namespace the client expects a return connect call. That was only happening during auto-connect, and not during normal server connections. Now the code correctly returns a connection to the client for every successful server connection.
Updates the tests so they reflect the change in how namespaces are processed. The packet tests are more flexible (like the SocketIO server tests). Added an extra check around polling in the server tests, so they aren't flaky.
[fixes #61]
=> Fix the SocketIO connect protocol

callback/callback.go, callback/callback_test.go
The callback wrap method didn't understand the map type when doing reflection. This commit adds the map type and serializes to JSON so that the Unserialize() on the map object will work as expected.
NOTE: that custom Serialize() and Unserialize() objects can be always used instead of the generic callback.Wrap struct. Examples were added to the callback_test.go file.
[ fixes #66 ]
=> Update the callback.Wrap struct to work with maps

engineio/option.go, engineio/option.v2.go, internal/option/option.go, option.v1.go, server.v1_test.go, server.v2_test.go, server.v3_test.go, server.v4_test.go
The engineio.WithPath option would change the internal EngineIO path, but left the internal SocketIO path untouched which caused issues with the service because the SocketIO and EngineIO internal paths didn't match.
This commit adds a socketio.WithPath option to change SocketIO paths (and the underlining EngineIO path).
This commit also abstracts the EngineIO WithPath option to guarantee that the code will compile even if the option is removed when building a specific version of the library. In this case it's not really important, but this is to showcase how it will work for new and refactored options.
Tests around adding the socketio.WithPath have been added separately outside of the integration tests, because they are testing a specific server configuration rather than a SocketIO …
=> Add a socketio.WithPath to change the SIO path

server.go, server_benchmark_test.go, session/session.go
The prefix is encoded to present ASCII characters during logging. The unicode characters can still be seen, by using GoString() or the "%#v" formatting function for the `log` and `fmt` Printf() function.
The prefix generator function was refactored to accept an injected date, for testing purposes.
Updating the prefix via a user function has not been implemented, as the ID type needs to change to accommodate this request. Providing a user function will be in a future commit.
[fixes #69]
=> Encode the SIO socketID generated prefix

README.md
Related to #50, provides an example on using a custom wrapper and event.
=> docs: Updated to include information on custom event callbacks

engineio/server.v2.go, engineio/server.v3.go, engineio/server.v4.go, engineio/sessions.go
When refactoring the transportSessions, there may be some updates to the doUpgrade function. This is a small PR getting that code inline for an update.
=> Refactor the doUpgrade transport return parameters
